"""
Reranker Fine-tuner

Fine-tune Qwen3-Reranker-0.6B trên pairwise preference data
từ interaction logs.

Loss: pairwise margin ranking loss
  L = -log σ(score(q, pos) - score(q, neg)) * weight

Trainer hỗ trợ:
  - Full fine-tuning (nhỏ, 0.6B tham số)
  - LoRA fine-tuning (tiết kiệm memory)
"""

from __future__ import annotations

import json
import os
from typing import List, Optional

import torch
import torch.nn as nn
import torch.nn.functional as F
from torch.utils.data import DataLoader, Dataset

from retrieval.reranker import Qwen3RerankerForTraining, _USER_TEMPLATE, _SYSTEM_PROMPT


# ---------------------------------------------------------------------------
# Dataset
# ---------------------------------------------------------------------------

class RankerPairDataset(Dataset):
    """
    Dataset of (query, positive_text, negative_text, weight) tuples.
    Loaded from JSONL file generated by PreferenceConverter.
    """

    def __init__(self, jsonl_path: str):
        self.samples = []
        with open(jsonl_path, "r", encoding="utf-8") as f:
            for line in f:
                line = line.strip()
                if line:
                    self.samples.append(json.loads(line))

    def __len__(self) -> int:
        return len(self.samples)

    def __getitem__(self, idx: int) -> dict:
        s = self.samples[idx]
        return {
            "query": s["query"],
            "positive": s["positive_text"],
            "negative": s["negative_text"],
            "weight": float(s.get("weight", 1.0)),
        }


# ---------------------------------------------------------------------------
# Trainer
# ---------------------------------------------------------------------------

class RerankerTrainer:
    """
    Fine-tune Qwen3-Reranker-0.6B on pairwise preference data.

    Parameters
    ----------
    model_id      : HuggingFace model or local path
    device        : "cpu" | "cuda"
    use_lora      : enable LoRA fine-tuning (requires peft library)
    lora_r        : LoRA rank
    lora_alpha    : LoRA scaling
    lr            : learning rate
    max_length    : max tokenizer length
    """

    def __init__(
        self,
        model_id: str = "Qwen/Qwen3-Reranker-0.6B",
        device: str = "cpu",
        use_lora: bool = True,
        lora_r: int = 16,
        lora_alpha: int = 32,
        lr: float = 2e-5,
        max_length: int = 512,
    ):
        self.device = device
        self.max_length = max_length

        self.model = Qwen3RerankerForTraining(model_id, device).to(device)

        if use_lora:
            self._apply_lora(lora_r, lora_alpha)

        self.optimizer = torch.optim.AdamW(
            filter(lambda p: p.requires_grad, self.model.parameters()),
            lr=lr,
            weight_decay=1e-2,
        )

    # ------------------------------------------------------------------
    def _apply_lora(self, r: int, alpha: int) -> None:
        try:
            from peft import LoraConfig, get_peft_model, TaskType
        except ImportError as e:
            raise ImportError("Install peft: pip install peft") from e

        config = LoraConfig(
            task_type=TaskType.CAUSAL_LM,
            r=r,
            lora_alpha=alpha,
            target_modules=["q_proj", "v_proj", "k_proj", "o_proj"],
            lora_dropout=0.05,
            bias="none",
        )
        self.model.model = get_peft_model(self.model.model, config)
        self.model.model.print_trainable_parameters()

    # ------------------------------------------------------------------
    def _compute_loss(
        self,
        queries: List[str],
        positives: List[str],
        negatives: List[str],
        weights: torch.Tensor,
    ) -> torch.Tensor:
        """
        Pairwise margin ranking loss.
        L = -Σ w_i * log σ(score(q_i, pos_i) - score(q_i, neg_i))
        """
        # Score positives
        enc_pos = self.model.encode_pairs(queries, positives, self.max_length)
        enc_pos = {k: v.to(self.device) for k, v in enc_pos.items()}
        pos_scores = self.model.forward_scores(**enc_pos)   # (B,)

        # Score negatives
        enc_neg = self.model.encode_pairs(queries, negatives, self.max_length)
        enc_neg = {k: v.to(self.device) for k, v in enc_neg.items()}
        neg_scores = self.model.forward_scores(**enc_neg)   # (B,)

        # Pairwise loss (weighted)
        diff = pos_scores - neg_scores                       # (B,)
        loss = -(F.logsigmoid(diff) * weights.to(self.device)).mean()
        return loss

    # ------------------------------------------------------------------
    def train(
        self,
        train_path: str,
        val_path: Optional[str] = None,
        num_epochs: int = 3,
        batch_size: int = 8,
        save_dir: str = "checkpoints/reranker",
        log_every: int = 20,
    ) -> None:
        train_ds = RankerPairDataset(train_path)
        train_loader = DataLoader(train_ds, batch_size=batch_size, shuffle=True)

        val_loader = None
        if val_path and os.path.exists(val_path):
            val_ds = RankerPairDataset(val_path)
            val_loader = DataLoader(val_ds, batch_size=batch_size)

        os.makedirs(save_dir, exist_ok=True)
        best_val_loss = float("inf")

        for epoch in range(1, num_epochs + 1):
            self.model.train()
            total_loss = 0.0

            for step, batch in enumerate(train_loader):
                queries = batch["query"]
                positives = batch["positive"]
                negatives = batch["negative"]
                weights = batch["weight"].float()

                loss = self._compute_loss(queries, positives, negatives, weights)

                self.optimizer.zero_grad()
                loss.backward()
                nn.utils.clip_grad_norm_(self.model.parameters(), 1.0)
                self.optimizer.step()

                total_loss += loss.item()
                if log_every and step % log_every == 0:
                    print(f"  Epoch {epoch} step {step:4d} | loss={loss.item():.4f}")

            avg_train = total_loss / max(len(train_loader), 1)
            print(f"Epoch {epoch} | avg_train_loss={avg_train:.4f}")

            if val_loader:
                val_loss = self._evaluate(val_loader)
                print(f"           | val_loss={val_loss:.4f}")
                if val_loss < best_val_loss:
                    best_val_loss = val_loss
                    self._save(os.path.join(save_dir, "best"))
                    print("  *** Saved best model ***")

        self._save(os.path.join(save_dir, "final"))

    # ------------------------------------------------------------------
    @torch.no_grad()
    def _evaluate(self, loader: DataLoader) -> float:
        self.model.eval()
        total = 0.0
        for batch in loader:
            queries = batch["query"]
            positives = batch["positive"]
            negatives = batch["negative"]
            weights = batch["weight"].float()
            loss = self._compute_loss(queries, positives, negatives, weights)
            total += loss.item()
        return total / max(len(loader), 1)

    def _save(self, path: str) -> None:
        os.makedirs(path, exist_ok=True)
        self.model.model.save_pretrained(path)
        self.model.tokenizer.save_pretrained(path)
        print(f"Saved model -> {path}")
